### ISSUE TITLE
NSString+Karelia.h missing from download

### ISSUE THREAD

**Issue by littlebigapps** [karelia/KSHTMLWriter#1]
Hey there,

I'm getting an error when importing KSHTMLWriter into an XCode Project...

'NSString+Karelia.h' file not found

Could you point me in the direction of this please?

Cheers,
Ant

**Comment by mikeabdullah** [comment]
Apologies, I don't know how that snuck in! Removed.

**Comment by littlebigapps** [comment]
Hi Mike,

Thanks for updating that..

I grabbed the latest download but when adding it to my project I'm now getting: 

KSXMLWriterDOMAdaptor.m:
cannot find interface declaration for 'DOMNode'

**Comment by mikeabdullah** [comment]
Do you want to integrate with WebKit?

If no, don't add that file to your project
If yes, you need to link to WebKit.framework for that file to compile

**Comment by littlebigapps** [comment]
Ah ok, gotcha, cheers :)
