### ISSUE TITLE
writeJavascriptWithContent is unclear..

### ISSUE THREAD

**Issue by mralexgray** [karelia/KSHTMLWriter#5]
the signature is `- (void)writeJavascriptWithContent:(void (^)(void))content;`

What are you supposed to do in the void block?

Wouldn't it make more sense...

```
- (void)writeJavascripString:(NSString*)script;
```

to which you would provide the script's source.

I know I'm just "not getting it".. can you help?

**Comment by mralexgray** [comment]
Oh wait..  i Just saw `writeJavascript:useCDATA:`  is that what I was looking for?

**Comment by mikeabdullah** [comment]
I've pushed some updated documentation for the methods: https://github.com/karelia/KSHTMLWriter/commit/8e8899242ab15a9c02f71fc3042892de54763942

Does that clear it up for you?

**Comment by mralexgray** [comment]
yes, thanks.  i'll go ahead and close this.  wondering... are you open to a pull that would simplify / reduce some of the code generation syntax?

**Comment by mikeabdullah** [comment]
Perhaps. What sort of simplification do you have in mind?

**Comment by mralexgray** [comment]
Not 100% sure..  off the top of my head... maybe some things along the lines of...

```
[self writeElementsWithClassesAndContent:@[
    @{ @"div" : @[@[@"arrayClass",@"container"],
        @{@"section" : @[@"example",
            @{@"div": @[@"stringClass",
                @{@"div":@[@"brick",1 % 2 ? @"small" : @"large", @"Some text content, or whatever"]},
            ]},
        ]},
    ]},
    @{@"div":@[NSNull.null, @"Aother Div with Text"]}]
];
```

**Comment by mikeabdullah** [comment]
If I'm perfectly honest, I can't make head or tail of this :(
I consider the existing syntax to be pretty straightforward:

```
[writer writeElement:@"div" idName:nil className:@"foo bar" content:^{
    // write some more things here
}];
```

My suspicion from your code sample is you'd like to avoid using blocks?

I have to admit I was thinking more along the lines of making some of the method names slightly clearer, such as:

```
-writeExternalJavascriptWithSrc:encoding:
-writeInlineJavascript:
```

**Comment by mralexgray** [comment]
Why is every line a block?  Does it have to do with the lower-level buffering that you do in more complex scenarios?  I guess I sort of dont see why the content argument isn't just a string..

**Comment by mikeabdullah** [comment]
Before blocks, it used to be done transactionally:

```
[writer startElement:@"div" className:@"foo bar"];
[writer writeText:@"Test:];
// write other things as needed
[writer endElement];
```

The block-based API makes that a little more convenient by providing automatic indentation, and saves you ever forgetting to call `-endElement`.

Inside of an element, clients need to be able to carry out arbitrary actions, including things like `if` statements. Without that flexibility, the client is forced to entirely assemble some sort of pseudo representation of the HTML in-memory. That rather defeats the point of KSHTMLWriter's deliberately streaming nature.

**Comment by mikeabdullah** [comment]
Oh, and there's `-writeElement:text:` should you have the simple case of plain text inside an element.

**Comment by mralexgray** [comment]
Oh, nice. You should check out `JATemplate`..  It does some REALLY cool string manipulation / concatenation stuff.

**Comment by mikeabdullah** [comment]
We have little need for such tempting in our app, so I guess KSHTMLWriter's API probably seems a bit weird then that it makes no attempt at it. Hopefully JATemplate and KSHTMLWriter play nicely together.
